### PR TITLE
Remove?: dsVideo: Adding Enhanced Error Code Flag Support

### PR DESCRIPTION
**Pull request by drissya-k**

### CODE REVIEW

**Comment by Ulrond** [comment]
what's this for? it's not the right way round? -> feature/gh43 shoudl contain this change? by pushing it on the branch?

**Review by Ulrond — CHANGES_REQUESTED** [review]
something broken here, put the changes directly on `[feature/gh43_enhancedenum_disable](https://github.com/rdkcentral/rdk-halif-test-device_settings/tree/feature/gh43_enhancedenum_disable)`

Remove `patch-1` branch

rdkcentral/ut-core#55 -> please update to support the KVP module , so we can commit this code as a valid upgrade, that can change configuration at runtime.

**Comment by Ulrond** [comment]
can we delete this? -> https://github.com/rdkcentral/rdk-halif-test-device_settings/pull/45/files#diff-0f1b23e0228132f769c5e898d4f8b3610c83eb368b64bcb2b93cf933e75e98d0

**Comment by hari22yuva** [comment]
something broken here, put the changes directly on [feature/gh43_enhancedenum_disable](https://github.com/rdkcentral/rdk-halif-test-device_settings/tree/feature/gh43_enhancedenum_disable)

Remove patch-1 branch, you also need an issue raised

This is what would have to happen to your new feature branch

**Pull request closed without merging**
