### PR TITLE
gh #251 dsHost: L3 Python test updates

### PR DESCRIPTION
**Pull request by hgfell683**
Update L3 tests addressing the following:

ut_raft update : ConfigRead API return attributes instead of dictionary, update test code accordingly.
Move the artifacts binary download to dsClass - Use utBaseUtils class if needed
Create Summary logging object required for testController from the test class.

### CODE REVIEW

**Comment by hari22yuva** [comment]
> _ No description provided. _

please add description about the PR

**Review by hari22yuva — COMMENTED** [review]
please check the review comments

**Review by hari22yuva — APPROVED** [review]
looks ok

**Review by srinivasgtl — APPROVED** [review]
Approving it.  For now the moduleConfigProfileFile is not required for this module, but just leaving it to be in sync with other modules.

**Pull request merged**
